### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by lakshmidintakurti**
please look at the doctor login html page and correct if any mistakes are there
@koteswararaoputta look at the functionality of html page
@nanichinna improve the table format

### CODE REVIEW

**Review by nanichinna — COMMENTED** [review]
@yedesavv  laa

**Comment by nanichinna** [comment]
whats up

**Comment by lakshmidintakurti** [comment]
first do your assigned work

**Comment by nanichinna** [comment]
better go to hostel and had lunch

**Pull request merged**
